
// actions/actionTypes

export const FETCH_POSTS_REQUEST='FETCH_POSTS_REQUEST'
export const FETCH_POSTS_FULFILLED='FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED='FETCH_POSTS_REJECTED'

export const FETCH_POST_REQUEST='FETCH_POST_REQUEST'
export const FETCH_POST_FULFILLED='FETCH_POST_FULFILLED'
export const FETCH_POST_REJECTED='FETCH_POST_REJECTED'

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";


export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_FULFILLED = 'CREATE_USER_FULFILLED'
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED'

export const LOGOUT_USER = 'LOGOUT_USER'