
// actions/actionTypes

export const FETCH_POSTS_REQUEST='FETCH_POSTS_REQUEST'
export const FETCH_POSTS_FULFILLED='FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED='FETCH_POSTS_REJECTED'

export const FETCH_POST_REQUEST='FETCH_POST_REQUEST'
export const FETCH_POST_FULFILLED='FETCH_POST_FULFILLED'
export const FETCH_POST_REJECTED='FETCH_POST_REJECTED'

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";


export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_FULFILLED = 'CREATE_USER_FULFILLED'
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED'


export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_FULFILLED = "CREATE_POST_FULFILLED";
export const CREATE_POST_REJECTED = "CREATE_POST_REJECTED";


// Edit post actiontypes
export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_FULFILLED = "EDIT_POST_FULFILLED";
export const EDIT_POST_REJECTED = "EDIT_POST_REJECTED";



// Create comment
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_FULFILLED = "CREATE_COMMENT_FULFILLED";
export const CREATE_COMMENT_REJECTED = "CREATE_COMMENT_REJECTED";

export const LOGOUT_USER = 'LOGOUT_USER'