
// actions/actionTypes

export const FETCH_POSTS_REQUEST='FETCH_POSTS_REQUEST'
export const FETCH_POSTS_FULFILLED='FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED='FETCH_POSTS_REJECTED'

export const FETCH_POST_REQUEST='FETCH_POST_REQUEST'
export const FETCH_POST_FULFILLED='FETCH_POST_FULFILLED'
export const FETCH_POST_REJECTED='FETCH_POST_REJECTED'